services:
  vcvq:
    container_name: vcvq
    build: .
    ports:
      - "${PORT:-3030}:3030"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=${PORT:-3030}
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
